<?php

use Illuminate\Database\Seeder;

class WatchesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Watch::create(['name'=>'Cellini', 'slogan'=>'Het klassieke horloge', 'price'=>'24750.00', 'description'=>'De Cellini-collectie heeft de oneindige elegantie van een traditioneel uurwerk gecombineerd met een modern tintje.', 'minidescription'=>'De naam van het horloge is geïnspireerd op de Italiaanse renaissance­kunstenaar, Benvenuto Cellini.', 'category_id'=>'1', 'photo_id'=>'1', 'videolink'=>'classic_watches_cellini.mp4', 'fluidimage'=>'fluid_cellini.png', 'detailimage'=>'detail_cellini.jpg', 'detailtitel'=>'Moonphase', 'detailtext'=>'De Cellini "Moonphase" is uitgerust met een uitzonderlijke reeks materialen van topkwaliteit. Het horloge bezit echter één onderdeel dat de drager in zijn verbeelding zelfs mee kan voeren naar een plek ver buiten tijd en ruimte: de meteoriet­ijzeren schijf die de volle maan afbeeldt.', 'fullimage'=>'full_cellini.jpg']);
        App\Watch::create(['name'=>'Datejust', 'slogan'=>'De referentie voor het klassieke horloge', 'price'=>'11750.00',  'description'=>'De Datejust al jaren bij de tijd, terwijl hij aan de codes blijft voldoen die hem, met name in de traditionele versies, tot een van de bekendste en herkenbaarste horloges maken.','minidescription'=>'De Datejust is dankzij zijn uitstraling en functies niet aan de mode onderhevig.', 'category_id'=>'1', 'photo_id'=>'2', 'videolink'=>'classic_watches_datejust.mp4', 'fluidimage'=>'fluid_datejust.png', 'detailimage'=>'detail_datejust.jpg', 'detailtitel'=>'Rolesor', 'detailtext'=>'Rolesor, de combinatie van goud met staal op een Rolex-horloge is kenmerkend voor het merk sinds 1933, toen de naam werd geregistreerd. Het is een prachtige combinatie van twee metalen: het ene edel, kostbaar en aantrekkelijk vanwege zijn glans en stabiliteit; het andere uiterst slijtvast en bekend om zijn sterkte en betrouwbaarheid.', 'fullimage'=>'full_datejust.jpg']);
        App\Watch::create(['name'=>'Day-Date', 'slogan'=>'Het ultieme prestigehorloge', 'price'=>'32200.00',  'description'=>'De Day-Date werd geïntroduceerd in 1956. Dit model was de eerste waterdichte en automatische polschronometer met een moderne kalender.', 'minidescription'=>'Deze gaf behalve de datum ook een in het venster op de wijzerplaat volledig uitgeschreven dagaanduiding weer.', 'category_id'=>'1', 'photo_id'=>'3', 'videolink'=>'classic_watches_day-date.mp4', 'fluidimage'=>'fluid_daydate.png', 'detailimage'=>'detail_daydate.jpg', 'detailtitel'=>'Goud of Platina', 'detailtext'=>'De Day-Date, die uitsluitend verkrijgbaar is in 18 kt goud of 950 platina, was het eerste polshorloge waarbij de datum en de dag van de week volledig werd uitgeschreven in een venster op de wijzerplaat. Het blijft bij uitstek het horloge voor invloedrijke mensen.', 'fullimage'=>'full_daydate.jpg']);
        App\Watch::create(['name'=>'Sky-Dweller', 'slogan'=>'Het horloge voor wereldreizigers', 'price'=>'45200.00',  'description'=>'De Sky-Dweller is een opvallend horloge dat zich onderscheidt door zijn tweede tijdzone op een niet-gecentreerde kleine schijf op de wijzerplaat.', 'minidescription'=>'Het horloge is ook uitgerust met het innovatieve en unieke Rolex-systeem om met behulp van de draaibare Ring Command-bezel functies in te stellen.', 'category_id'=>'1', 'photo_id'=>'4', 'videolink'=>'classic_watches_sky-dweller.mp4', 'fluidimage'=>'fluid_skydweller.png', 'detailimage'=>'detail_skydweller.jpg', 'detailtitel'=>'Saros-jaarkalender', 'detailtext'=>'Een opvallend kenmerk van de Saros-jaarkalender is een dieprode rechthoek in één van de 12 vensters rondom de wijzerplaat die de maand aangeeft. Het ingenieuze mechanisme maakt het leven voor de drager gemakkelijker. De gebruiker hoeft er niet meer aan te denken de datum te verzetten aan het eind van een maand met 30 dagen.', 'fullimage'=>'full_skydweller.jpg']);
        App\Watch::create(['name'=>'Pearlmaster', 'slogan'=>'De parel uit de Oyster-collectie', 'price'=>'38500.00',  'description'=>'De Pearlmaster neemt een bijzondere plaats in in de Oyster-collectie. Dit model is niet zo maar een horloge, het is een sieraad dat elegantie en finesse uitstraalt.', 'minidescription'=>'Deze horloge vertegenwoordigt met zijn edelmetalen en -stenen het toppunt van schoonheid.', 'category_id'=>'1', 'photo_id'=>'5', 'videolink'=>'classic_watches_pearlmaster.mp4', 'fluidimage'=>'fluid_pearlmaster.png', 'detailimage'=>'detail_pearlmaster.jpg', 'detailtitel'=>'Diamanten', 'detailtext'=>'De diamanten die de Pearlmaster sieren, worden geselecteerd op basis van strenge criteria en gezet volgens de beste tradities om de meest intense schittering te garanderen. Rolex heeft zijn eigen edelsteen­laboratorium, waar ervaren specialisten de kwaliteit van de edelstenen controleren.', 'fullimage'=>'full_pearlmaster.jpg']);
        App\Watch::create(['name'=>'Air-King', 'slogan'=>'Een eerbetoon aan de luchtvaart', 'price'=>'9700.00',  'description'=>'De Rolex Air-King is een eerbetoon aan de luchtvaartpioniers en de rol van de Oyster tijdens het epische verhaal van de luchtvaart.', 'minidescription'=>'Met zijn 40 mm kast van Oystersteel-staal, zijn Oyster-band met massieve schakels en Oysterclasp-sluiting, laat de Air-King heet luchtvaarterfgoed van de oorspronkelijke Rolex Oyster voortleven.', 'category_id'=>'2', 'photo_id'=>'6', 'videolink'=>'professional_watches_air-king.mp4', 'fluidimage'=>'fluid_airking.png', 'detailimage'=>'detail_airking.jpg', 'detailtitel'=>'Wijzerplaat', 'detailtext'=>'De Air-King heeft een kenmerkende zwarte wijzerplaat met grote 3, 6 en 9 cijfers die de uren aangeven en een prominente minutenschaal om de navigatietijd af te lezen. De naam Air-King staat op de wijzerplaat en heeft hetzelfde, speciaal voor het model ontworpen, lettertype als de versie uit de jaren 50.', 'fullimage'=>'full_airking.jpg']);
        App\Watch::create(['name'=>'Cosmograph Daytona', 'slogan'=>'Een horloge gemaakt om te racen', 'price'=>'15600.00',  'description'=>'De Cosmograph Daytona is het ultieme multifunctionele horloge voor iedereen met een passie voor racen en snelheid.', 'minidescription'=>'Dit horloge, die werd geïntroduceerd in 1963, is ontworpen om aan de eisen van professionele autocoureurs te voldoen.', 'category_id'=>'2', 'photo_id'=>'7', 'videolink'=>'professional_watches_cosmograph_daytona.mp4', 'fluidimage'=>'fluid_cosmographdaytona.png', 'detailimage'=>'detail_cosmographdaytona.jpg', 'detailtitel'=>'Chronograaf', 'detailtext'=>'De uitstekende prestaties van kaliber 4130 zijn voornamelijk te danken aan het gebruik van een verticale, in plaats van een laterale, koppeling om de chronograaf te activeren.', 'fullimage'=>'full_cosmographdaytona.jpg']);
        App\Watch::create(['name'=>'Milgauss', 'slogan'=>'Een eerbetoon aan de wetenschap', 'price'=>'7550.00',  'description'=>'De Rolex Milgauss werd ontworpen om aan de eisen van de wetenschappelijke wereld te voldoen.', 'minidescription'=>'Het horloge is bestand tegen magnetische velden tot wel 1000 gauss. De betrouwbaarheid en precisie van een gewoon mechanisch horloge kan worden beïnvloed door een magnetisch veld van 50 tot 100 gauss.', 'category_id'=>'2', 'photo_id'=>'8', 'videolink'=>'professional_watches_milgauss.mp4', 'fluidimage'=>'fluid_milgauss.png', 'detailimage'=>'detail_milgauss.jpg', 'detailtitel'=>'Oranje bliksemschicht', 'detailtext'=>'Trouw aan zijn wetenschappelijke erfgoed. De Milgauss is tijdens zijn ontwikkeling trouw gebleven aan zijn wetenschappelijk erfgoed en unieke identiteit. Met zijn strakke lijnen en suggestieve oranje seconde­wijzer in de vorm van een bliksemschicht als herinnering aan het originele model, is de Milgauss in een oogopslag te herkennen.', 'fullimage'=>'full_milgauss.jpg']);
        App\Watch::create(['name'=>'Sea-Dweller', 'slogan'=>'Een horloge dat de diepte wist te overwinnen', 'price'=>'14850.00',  'description'=>'De Sea-Dweller en Rolex Deepsea zijn extreem sterke duikhorloges die door Rolex werden ontwikkeld voor diepzee­onderzoek.', 'minidescription'=>'Met een waterdichtheid tot een diepte van 3900 meter voor deze Rolex, is dit horloge het bewijs van Rolex’ leiderschap op het gebied van duikhorloges en het resultaat van jarenlange samenwerking met duik­professionals.', 'category_id'=>'2', 'photo_id'=>'9', 'videolink'=>'professional_watches_sea-dweller.mp4', 'fluidimage'=>'fluid_seadweller.png', 'detailimage'=>'detail_seadweller.jpg', 'detailtitel'=>'Chromalight', 'detailtext'=>'Om ook in het donker goed afleesbaar te zijn, is de gesoigneerde zwarte wijzerplaat uitgerust met grote Chromalight uurmarkeringen en wijzers die zijn opgevuld met lichtgevend materiaal dat langdurig een blauwe gloed uitstraalt.', 'fullimage'=>'full_seadweller.jpg']);
        App\Watch::create(['name'=>'Submariner', 'slogan'=>'Een icoon onder de duikhorloges', 'price'=>'12450.00',  'description'=>'De Submariner is een icoon onder de duikhorloges. Het is het horloge dat een grote rol heeft gespeeld bij het toegankelijk maken van de onderwater­wereld.', 'minidescription'=>'De Submariner werd gelanceerd in 1953 en was het eerste duikhorloge dat tot een diepte van 100 meter waterdicht was', 'category_id'=>'2', 'photo_id'=>'10', 'videolink'=>'professional_watches_submariner.mp4', 'fluidimage'=>'fluid_submariner.png', 'detailimage'=>'detail_submariner.jpg', 'detailtitel'=>'Beter afleesbaarheid', 'detailtext'=>'Het lichtgevende Chromalight-display op de wijzerplaat zorgt voor een betere afleesbaarheid in het donker, wat voor duikers van wezenlijk belang is. De uurmarkeringen met eenvoudige vormen – driehoeken, cirkels of rechthoeken – en de brede uur- en minuutwijzers zorgen ervoor dat het horloge direct en eenvoudig af te lezen is en het risico op verwarring onder water wordt vermeden.', 'fullimage'=>'full_submariner.jpg']);
    }
}
